channels:
  - conda-forge
  - torch
dependencies:
  - pytorch=1.12
  - cudatoolkit=10.2
  - torchvision
  - pip
  - pip:
    - wandb
    - stable-baselines3
    - pytorch-lightning
    - imageio
    - -e .