channels:
  - pytorch
  - conda-forge
dependencies:
  - pytorch=1.12
  - cudatoolkit=10.2
  - torchvision
  - pip
  - pip:
    - wandb
    - stable-baselines3
    - pytorch-lightning
    - imageio
    - albumentations
    - timm
    - pytest
    - pre-commit
    - -e .